import 'package:flutter/material.dart';

import 'network_services.dart';
import 'top_apps_json_parser.dart';
import 'app_details.dart';

class AppList extends StatelessWidget {
  AppList({Key key, @required data}) : super(key: key);

  Widget networkBuild() {
    return FutureBuilder(
      future: fetch(),
      builder: (context, AsyncSnapshot<Autogenerated> snapshot) {
        if (!snapshot.hasData) return new Container();
        List<Entry> apps = snapshot.data.feed.entry;
        return new ListView.builder(
          itemCount: apps.length,
          itemBuilder: (context, index) {
            return ListTile(
              leading: Image.network('${apps[index].imImage[0].label}'),
              title: Text('${apps[index].imName.label}'),
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                      builder: (context) => AppDetails(app: apps[index]),
                      fullscreenDialog: true),
                );
              },
            );
          },
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          appBar: AppBar(
            title: Text('Top Apps List'),
          ),
          body: networkBuild()),
    );
  }
}
