import 'package:flutter/material.dart';

import 'app_list.dart';
import 'top_apps_json_parser.dart';

void main() {
  Future<Autogenerated> data;

  runApp(MaterialApp(
    home: AppList(data: data),
    title: 'Top Apps Viewer',
  ));
}