import 'package:http/http.dart' as http;
import 'top_apps_json_parser.dart';
import 'dart:convert';

Future<Autogenerated> fetch() async {
  final response = await http
      .get('https://itunes.apple.com/fr/rss/toppaidapplications/limit=50/json');
  return Autogenerated.fromJson(json.decode(response.body));
}

